use sha2::{Digest, Sha256};
use std::env;
use std::fs;
use std::path::Path;

// rotate left byte
fn rol_byte(byte: u8, shift: u8) -> u8 {
	byte.rotate_left(shift as u32)
}

fn main() {
	// --- SHIFT_KEY ---
	let shift_key = env::var("VICUUTRUYENREBORN_SHIFT_KEY")
		.ok()
		.and_then(|v| v.parse::<u8>().ok())
		.unwrap_or(0);

	// --- MASTER_KEY_HASH ---
	let master = env::var("VICUUTRUYENREBORN_MASTER_KEY").expect("Missing MASTERVICUUTRUYENREBORN_MASTER_KEY_KEY env variable");
	let hash = Sha256::digest(master.as_bytes());
	let hash_bytes_shifted: Vec<u8> = hash.iter().map(|b| rol_byte(*b, shift_key)).collect();

	// --- Write to src/env.rs ---
	let dest_path = Path::new("src/crypto").join("env.rs");
	let contents = format!(
		"// Auto-generated by build.rs (bytes rotated by SHIFT_KEY)\n\
        pub const MASTER_KEY_HASH_SHIFTED: &[u8] = &{:?};\n\
        pub const SHIFT_KEY: u8 = {};\n",
		hash_bytes_shifted, shift_key
	);

	fs::write(&dest_path, contents).expect("Failed to write src/crypto/env.rs");
}
