#!/usr/bin/env bash
set -e

# --- CONFIG ---
SHIFT_KEY="${VICUUTRUYENREBORN_SHIFT_KEY:-0}"          # default 0 if not set
MASTER_KEY="${VICUUTRUYENREBORN_MASTER_KEY:?VICUUTRUYENREBORN_MASTER_KEY env variable not set}"  # exit if not set

# --- SHA256 ---
# Compute SHA256 as raw bytes
hash_bytes=($(echo -n "$VICUUTRUYENREBORN_MASTER_KEY" | sha256sum | awk '{print $1}'))

# Convert hex to decimal bytes
hash_bytes_dec=()
for h in "${hash_bytes[@]}"; do
    # Split hex string into bytes
    for ((i=0; i<${#h}; i+=2)); do
        byte="0x${h:$i:2}"
        # Rotate left by SHIFT_KEY bits
        rotated=$(( ((byte << SHIFT_KEY) | (byte >> (8-SHIFT_KEY))) & 0xFF ))
        hash_bytes_dec+=($rotated)
    done
done

# --- ALLOWED_DOMAINS_SHIFTED ---
# TODO: define allowed_bytes_shifted array or read from file
allowed_bytes_shifted=()  # empty for now

# --- Write to src/env.rs ---
mkdir -p src
{
    echo "// Auto-generated by build.sh (bytes rotated by SHIFT_KEY)"
    echo -n "pub const MASTER_KEY_HASH_SHIFTED: &[u8] = &["
    printf "%s," "${hash_bytes_dec[@]}"
    echo "];"
    echo "pub const ALLOWED_DOMAINS_SHIFTED: &[u8] = &[${allowed_bytes_shifted[*]}];"
    echo "pub const SHIFT_KEY: u8 = $SHIFT_KEY;"
} > src/env.rs

echo "src/env.rs generated successfully!"

cargo +nightly build --release
mkdir -p target/wasm32-unknown-unknown/release/Payload
cp res/* target/wasm32-unknown-unknown/release/Payload
cp target/wasm32-unknown-unknown/release/*.wasm target/wasm32-unknown-unknown/release/Payload/main.wasm
cd target/wasm32-unknown-unknown/release ; zip -r package.aix Payload
mv package.aix ../../../package.aix
